# -*- coding: utf-8 -*-
"""sdl3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHhk1GjtYGk7HkQrQUMo4wxVoUTXves4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style

from google.colab import files
uploaded=files.upload()

dataset=pd.read_csv('bank and employments.csv')
#print(dataset)

a=dataset.iloc[:,0]     #years
a1=dataset.iloc[:,1]    #Scheduled Banks - No. of Banks - Indian
a2=dataset.iloc[:,2]    #Scheduled Banks - No. of Banks - foreign
a3=dataset.iloc[:,3]    #Scheduled Banks - No. of Employees  - Indian
a4=dataset.iloc[:,4]    #Scheduled Banks - No. of Employees  - foreign

print(a1.describe())

#line graph
x1=a
y1=a1
plt.plot(x1, y1, label = "Indian scheduled banks") 
x2=a
y2=a2
plt.plot(x2, y2, label = "foreign scheduled banks") 
plt.xlabel('x - axis') 
plt.ylabel('y - axis')  
plt.title('SCHEDULED BANKS 2001-2016') 
plt.legend() 
plt.show()

#bar graph
plt.bar(a1,a3,label="changes in number of workers in indian banks",color='b')

plt.legend()
plt.xlabel('indian banks')
plt.ylabel('indian employees')

plt.show()

#scatter plot
x = a
y = a1
 
x1=a
y1=a2
 
plt.scatter(x,y, label='indian banks in year 2001-2016',color='r')
plt.scatter(x1,y1,label='foreign banks in year 2001-2016',color='b')
plt.xlabel('years')
plt.ylabel('banks')
plt.title('indian and foreign banks in years 2001-2016')
plt.legend()
plt.show()

#stack plot
 years =a
  
 indian_employees =a3
 foreign_employees =a4
 
  
 plt.plot([],[],color='m', label='indian_employees', linewidth=5)
 plt.plot([],[],color='c', label='foreign_employees', linewidth=5)
 
  
 plt.stackplot(years,indian_employees,foreign_employees, colors=['m','c'])
  
 plt.xlabel('x')
 plt.ylabel('y')
 plt.title('indian v/s foreign employees')
 plt.legend()
 plt.show()

#simple line graph
style.use('ggplot')
x1=a.values.reshape(-1,1)
y1=a2.values.reshape(-1,1)
#x = a
#y = a2
x2 = a.values.reshape(-1,1)
y2 = a4.values.reshape(-1,1)
plt.plot(x1,y1,'g',label='foreign banks', linewidth=5)
plt.plot(x2,y2,'c',label='foreign employes',linewidth=5)
plt.title('sheduled foreign banks and employees')
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.legend()
plt.grid(True,color='k')
plt.show()

#box plot
data1 = a1
data2 = a2

data = list([a1, a2])


fig, ax = plt.subplots()
ax.boxplot(data)
ax.set_title('indian and foreign banks')
ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
xticklabels=['indian banks', 'foreign banks']
ax.set_xticklabels(xticklabels)
ax.yaxis.grid(True)
plt.show()